name: Pockets CLI
release:
  current-version: 1.0.2
  next-version: 1.0.2
  snapshot-version: 199-SNAPSHOT
build:
  artifact: pockets-cli
jitpack:
  group: com.github.ebullient
  artifact: pockets-cli
toggle: false
